name: tutorial_coach_mark
description: Guide that helps you to present your app and its features in a beautiful, simple and customizable way. Tutorial | Guide | Coach.
version: 1.2.4
homepage: https://github.com/RafaelBarbosatec/tutorial_coach_mark

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # back_button_interceptor: ^6.0.1
  back_button_interceptor: ^5.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


